# Generated by Django 4.0.3 on 2022-04-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='salom', max_length=50)),
                ('desc', models.TextField(blank=True, default='salom')),
            ],
        ),
    ]
